### ISSUE TITLE
Stale didn't work for Github Enterprise

### ISSUE THREAD

**Issue by elsayed-atef** [probot/stale#146]
i made a deployment for stale to be used for github enterprise.
i used the env GHE_HOST to point to my github.
i can go to the URL and see the welcome page for stale and also the webhooks are delivered from github enterprise to stale URL.

i tested the configuration for public github and it worked didn't get what is wrong with the current deployment. i googled it but can't find help.

i can find these errors in the log
```
14:00:48.082Z ERROR probot: {"message":"'Expiration time' claim ('exp') must be a numeric value representing the future time at which the assertion expires","documentation_url":"https://developer.github.com/enterprise/2.13/v3"}
  HttpError: {"message":"'Expiration time' claim ('exp') must be a numeric value representing the future time at which the assertion expires","documentation_url":"https://developer.github.com/enterprise/2.13/v3"}
      at response.text.then.message (/stale/node_modules/@octokit/rest/lib/request/request.js:78:19)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)

	  
	  18:28:50.720Z ERROR event: {"message":"'Expiration time' claim ('exp') must be a numeric value representing the future time at which the assertion expires","documentation_url":"https://developer.github.com/enterprise/2.13/v3"} (id=2efb5660-86e0-xxxx-xxxx-edc04b936dcf)
  HttpError: {"message":"'Expiration time' claim ('exp') must be a numeric value representing the future time at which the assertion expires","documentation_url":"https://developer.github.com/enterprise/2.13/v3"}
      at response.text.then.message (/stale/node_modules/@octokit/rest/lib/request/request.js:78:19)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  --
  event: {
    "id": "2efb5660-86e0-xxxx-xxxx-edc04b936dcf",
    "event": "issues.opened",
    "repository": "xxxxx/test-stale",
    "installation": 3
  }
```

**Comment by bkeepers** [comment]
@sayed24 thanks for opening the issue. That is very strange. The error message seems to be from the request made to GitHub, and it's complaining about [this value](https://github.com/probot/probot/blob/master/src/github-app.ts#L6), which is supposed to be a future time.

Is there a way you can verify that the clock on the server running the probot app is accurate?

**Comment by sayed24** [comment]
Thanks @bkeepers , there was difference in clock between probot and the Github.
