### ISSUE TITLE
Missing getInstallations method in latest version of octokit

### ISSUE THREAD

**Issue by jakeswenson** [probot/stale#253]
I'm trying to add `probot-stale` as a [composed app](https://probot.github.io/docs/deployment/#combining-apps), but it's failng to load because `getInstallations` is not a function. It seems it was renamed to `listInstallations` according to this PR: https://github.com/angular/github-robot/commit/19f42906cb944f6b71730853e1efd9e77c25457d#diff-dc25f195229dc07dc2800f765f2fb98fL27

**Comment by jakeswenson** [comment]
Here is the exact error on startup: 
```
15:37:31.994Z ERROR probot: github.apps.getInstallations is not a function
  TypeError: github.apps.getInstallations is not a function
      at eachInstallation (/bot/node_modules/probot-scheduler/index.js:74:29)
```

**Comment by jakeswenson** [comment]
> Is this still relevant? 
Yes
> If so, what is blocking it? 
The Author of you.
> Is there anything you can do to help move it forward?
No, the latest version of github needs to be pushed to NPM! It's not a hard fix

**Comment by jakeswenson** [comment]
@JasonEtco ^

**Comment by jakeswenson** [comment]
yes

**Comment by TeodorHMX1** [comment]
yes

**Comment by rthadur** [comment]
I am facing the same issue , do you have any update ?

**Comment by jizusun** [comment]
I only have this problem when working with `stale` and `pr-triage`
```
❯ 06:36:04.951Z ERROR probot: github.apps.getInstallations is not a function                                                                     ─╯
  TypeError: github.apps.getInstallations is not a function
      at eachInstallation (/app/node_modules/stale/node_modules/probot-scheduler/index.js:74:29)

```

**Comment by rkoster** [comment]
please fix this

**Comment by rkoster** [comment]
Works when downgrading probot to match: https://github.com/probot/stale/blob/master/package.json#L21

**Comment by sgowroji** [comment]
Hi @rkoster, @jakeswenson @jakeswenson, Have you resolved this issue ? Am still seeing this? Could you please share the fix ?
