### ISSUE TITLE
Unable to access private repository

### ISSUE THREAD

**Issue by poloka** [probot/stale#352]
I'm currently getting the error message noted below when the scheduler is trying to pull a private repository.  Does probot support usage of GitHub tokens when accessing repositories?  I am on an enterprise github edition that does not support actions so please do not suggest actions.  

> The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.

```
{
  "name": "event",
  "hostname": "probotstale-dev-bot-5b978557d7-2jstq",
  "pid": 24,
  "level": 50,
  "err": {
    "message": "Validation Failed: {\"message\":\"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.\",\"resource\":\"Search\",\"field\":\"q\",\"code\":\"invalid\"}",
    "name": "HttpError",
    "stack": "HttpError: Validation Failed: {\"message\":\"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.\",\"resource\":\"Search\",\"field\":\"q\",\"code\":\"invalid\"}\n at /src/node_modules/@octokit/request/dist-node/index.js:86:21\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (internal/process/task_queues.js:95:5)\n at async Job.doExecute (/src/node_modules/bottleneck/light.js:405:18)",
    "code": 422
  },
  "event": {
    "event": "schedule.repository",
    "installation": 2391,
    "repository": "poloka/application-config"
  },
  "msg": "Validation Failed: {\"message\":\"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.\",\"resource\":\"Search\",\"field\":\"q\",\"code\":\"invalid\"}",
  "time": "2021-10-06T21:03:23.685Z",
  "v": 0
}
```

**Comment by poloka** [comment]
Is there any support for this app?  I am still experiencing the issue noted above and still not moving to actions.
